version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://vlsi_user:vlsi_password@db:5432/vlsi_hero
      - SESSION_SECRET=your-secret-key-here
      - FLASK_ENV=production
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vlsi_hero
      - POSTGRES_USER=vlsi_user
      - POSTGRES_PASSWORD=vlsi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static

volumes:
  postgres_data: